# Generated by Django 4.2.9 on 2026-02-27 05:11

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '超级管理员'), ('manager', '业务经理'), ('warehouse_manager', '仓库主管'), ('warehouse_staff', '仓库操作员'), ('customer_service', '客服')], default='warehouse_staff', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除'), ('status_change', '状态变更'), ('inbound', '入库'), ('outbound', '出库')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('target', models.CharField(max_length=100, verbose_name='操作对象')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('delivery_address', models.TextField(verbose_name='收货地址')),
                ('return_address', models.TextField(blank=True, verbose_name='回收地址')),
                ('event_date', models.DateField(verbose_name='活动日期')),
                ('rental_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='租赁天数')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='发货日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='回收日期')),
                ('ship_tracking', models.CharField(blank=True, max_length=100, verbose_name='发货单号')),
                ('return_tracking', models.CharField(blank=True, max_length=100, verbose_name='回收单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='订单总额')),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='已付押金')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='待收尾款')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('delivered', '已送达'), ('in_use', '使用中'), ('returned', '已归还'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='租金单价')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='押金单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部件名称')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('category', models.CharField(choices=[('main', '主体道具'), ('accessory', '配件'), ('consumable', '消耗品'), ('packaging', '包装材料'), ('other', '其他')], default='accessory', max_length=20, verbose_name='分类')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('safety_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='安全库存')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('last_inbound_date', models.DateField(blank=True, null=True, verbose_name='最近入库日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部件',
                'verbose_name_plural': '部件',
                'db_table': 'parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('adjustment', '调整')], max_length=20, verbose_name='类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('related_doc', models.CharField(blank=True, max_length=100, verbose_name='关联单据')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '部件流水',
                'verbose_name_plural': '部件流水',
                'db_table': 'parts_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('channel', models.CharField(choices=[('online', '网购平台'), ('secondhand', '闲鱼二手'), ('offline', '线下市场'), ('other', '其他')], max_length=20, verbose_name='来源渠道')),
                ('supplier', models.CharField(max_length=200, verbose_name='供应商/店铺')),
                ('link', models.URLField(blank=True, verbose_name='商品链接')),
                ('order_date', models.DateField(verbose_name='下单日期')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='到货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ordered', '已下单'), ('arrived', '已到货'), ('stocked', '已入库'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='部件名称')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
            ],
            options={
                'verbose_name': '采购单明细',
                'verbose_name_plural': '采购单明细',
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=100, verbose_name='SKU名称')),
                ('category', models.CharField(default='主题套餐', max_length=50, verbose_name='分类')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='租金')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='押金')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='总库存')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'skus',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键')),
                ('value', models.CharField(max_length=500, verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('gap_days', models.IntegerField(verbose_name='间隔天数')),
                ('cost_saved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='节省成本')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core.order', verbose_name='回收订单')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core.order', verbose_name='发货订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '转寄任务',
                'verbose_name_plural': '转寄任务',
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['code'], name='skus_code_1e00f4_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['is_active'], name='skus_is_acti_3e608d_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.part', verbose_name='部件'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder', verbose_name='采购单'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='partsmovement',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='partsmovement',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.part', verbose_name='部件'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='parts_categor_c0361c_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active'], name='parts_is_acti_7b1503_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transfers_status_868f65_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_no'], name='purchase_or_po_no_3c05e3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchase_or_order_d_409199_idx'),
        ),
        migrations.AddIndex(
            model_name='partsmovement',
            index=models.Index(fields=['part', 'created_at'], name='parts_movem_part_id_0dbb87_idx'),
        ),
        migrations.AddIndex(
            model_name='partsmovement',
            index=models.Index(fields=['type'], name='parts_movem_type_caae17_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='orders_order_n_a26108_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event_date'], name='orders_event_d_62b307_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='orders_custome_d85dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module'], name='audit_logs_module_f52b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
    ]
