# Generated by Django 4.2.9 on 2026-03-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sku_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_no",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="单套编号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_warehouse", "在库"),
                            ("in_transit", "在途"),
                            ("maintenance", "维修中"),
                            ("scrapped", "已报废"),
                        ],
                        default="in_warehouse",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_location_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "仓库"),
                            ("order", "订单"),
                            ("transit", "物流在途"),
                            ("unknown", "未知"),
                        ],
                        default="warehouse",
                        max_length=20,
                        verbose_name="当前位置类型",
                    ),
                ),
                (
                    "last_tracking_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="最近物流单号"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "库存单套实例",
                "verbose_name_plural": "库存单套实例",
                "db_table": "inventory_units",
                "ordering": ["sku_id", "unit_no"],
            },
        ),
        migrations.CreateModel(
            name="UnitMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WAREHOUSE_OUT", "仓库发出"),
                            ("TRANSFER_PENDING", "转寄待执行"),
                            ("TRANSFER_SHIPPED", "转寄寄出"),
                            ("TRANSFER_COMPLETED", "转寄完成"),
                            ("RETURN_SHIPPED", "回仓在途"),
                            ("RETURNED_WAREHOUSE", "已回仓"),
                            ("EXCEPTION", "异常"),
                        ],
                        max_length=30,
                        verbose_name="节点类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("warning", "预警"),
                            ("timeout", "超时"),
                            ("closed", "闭环完成"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="节点状态",
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="物流单号"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "event_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="节点时间"),
                ),
            ],
            options={
                "verbose_name": "单套流转日志",
                "verbose_name_plural": "单套流转日志",
                "db_table": "unit_movements",
                "ordering": ["-event_time"],
            },
        ),
        migrations.RenameIndex(
            model_name="transferallocation",
            new_name="transfer_al_source__c297ba_idx",
            old_name="transfer_al_source__fcb8bc_idx",
        ),
        migrations.RenameIndex(
            model_name="transferallocation",
            new_name="transfer_al_target__a3cc8e_idx",
            old_name="transfer_al_target__b72d17_idx",
        ),
        migrations.RenameIndex(
            model_name="transferallocation",
            new_name="transfer_al_target__ae1d6f_idx",
            old_name="transfer_al_target__bd9c91_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="event_date",
            field=models.DateField(verbose_name="预定日期"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("confirmed", "待发货"),
                    ("delivered", "已发货"),
                    ("in_use", "使用中"),
                    ("returned", "已归还"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AddField(
            model_name="unitmovement",
            name="from_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_moves_from",
                to="core.order",
                verbose_name="来源订单",
            ),
        ),
        migrations.AddField(
            model_name="unitmovement",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AddField(
            model_name="unitmovement",
            name="to_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_moves_to",
                to="core.order",
                verbose_name="目标订单",
            ),
        ),
        migrations.AddField(
            model_name="unitmovement",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_movements",
                to="core.transfer",
                verbose_name="关联转寄任务",
            ),
        ),
        migrations.AddField(
            model_name="unitmovement",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="core.inventoryunit",
                verbose_name="单套实例",
            ),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="current_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_units",
                to="core.order",
                verbose_name="当前归属订单",
            ),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="core.sku",
                verbose_name="SKU",
            ),
        ),
        migrations.AddIndex(
            model_name="unitmovement",
            index=models.Index(
                fields=["event_type", "status"], name="unit_moveme_event_t_485c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitmovement",
            index=models.Index(
                fields=["unit", "event_time"], name="unit_moveme_unit_id_2e7791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryunit",
            index=models.Index(
                fields=["sku", "status"], name="inventory_u_sku_id_d92e78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryunit",
            index=models.Index(
                fields=["current_order"], name="inventory_u_current_e723ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryunit",
            index=models.Index(
                fields=["is_active"], name="inventory_u_is_acti_d774dc_idx"
            ),
        ),
    ]
