# Generated by Django 4.2.9 on 2026-03-07 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_inventoryunit_unitmovement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SKUComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_set",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="单套用量",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sku_components",
                        to="core.part",
                        verbose_name="部件",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU部件组成",
                "verbose_name_plural": "SKU部件组成",
                "db_table": "sku_components",
                "ordering": ["sku_id", "part__name"],
                "indexes": [
                    models.Index(fields=["sku"], name="sku_compone_sku_id_05cf1d_idx"),
                    models.Index(
                        fields=["part"], name="sku_compone_part_id_541617_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="skucomponent",
            constraint=models.UniqueConstraint(
                fields=("sku", "part"), name="uniq_sku_part_component"
            ),
        ),
    ]
