# Generated by Django 4.2.9 on 2026-03-07 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_skucomponent_skucomponent_uniq_sku_part_component"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryUnitPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="应有数量",
                    ),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="实有数量",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("missing", "缺件"),
                            ("damaged", "损坏"),
                            ("lost", "丢失"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近盘点时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_unit_parts",
                        to="core.part",
                        verbose_name="部件",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_parts",
                        to="core.inventoryunit",
                        verbose_name="单套实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "单套部件状态",
                "verbose_name_plural": "单套部件状态",
                "db_table": "inventory_unit_parts",
                "ordering": ["unit_id", "part__name"],
                "indexes": [
                    models.Index(
                        fields=["unit", "is_active"],
                        name="inventory_u_unit_id_235c8d_idx",
                    ),
                    models.Index(
                        fields=["part"], name="inventory_u_part_id_0fc10a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="inventory_u_status_1fe41a_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryunitpart",
            constraint=models.UniqueConstraint(
                fields=("unit", "part"), name="uniq_unit_part_status"
            ),
        ),
    ]
