# Generated by Django 4.2.9 on 2026-03-07 11:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_inventoryunitpart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit_received", "收押金"),
                            ("balance_received", "收尾款"),
                            ("deposit_refund", "退押金"),
                            ("penalty_charge", "扣罚"),
                            ("manual_adjust", "人工调整"),
                        ],
                        max_length=30,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="金额",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="关联单号"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_transactions",
                        to="core.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "资金流水",
                "verbose_name_plural": "资金流水",
                "db_table": "finance_transactions",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["order", "transaction_type"],
                        name="finance_tra_order_i_73f615_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="finance_tra_created_41f97c_idx"
                    ),
                ],
            },
        ),
    ]
