# Generated by Django 4.2.9 on 2026-03-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_financetransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("delivered_recommend_change", "已发货改单挂靠"),
                            ("delivered_order_cancel", "已发货订单取消"),
                            ("frequent_cancel", "高频取消"),
                        ],
                        max_length=40,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="风险级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("processing", "处理中"),
                            ("closed", "已关闭"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="模块"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "event_data",
                    models.JSONField(blank=True, default=dict, verbose_name="事件数据"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "detected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events_detected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events",
                        to="core.order",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events",
                        to="core.transfer",
                        verbose_name="关联转寄任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险事件",
                "verbose_name_plural": "风险事件",
                "db_table": "risk_events",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "level"], name="risk_events_status_21fef2_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="risk_events_event_t_1c0213_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="risk_events_order_i_01d212_idx",
                    ),
                ],
            },
        ),
    ]
