# Generated by Django 4.2.9 on 2026-03-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_riskevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="审批单号"
                    ),
                ),
                (
                    "action_code",
                    models.CharField(max_length=50, verbose_name="动作编码"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="模块"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=50, verbose_name="目标类型"),
                ),
                ("target_id", models.IntegerField(verbose_name="目标ID")),
                (
                    "target_label",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="目标标识"
                    ),
                ),
                ("summary", models.CharField(max_length=200, verbose_name="摘要")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="审批参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("executed", "已执行"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "review_note",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="审批备注"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="执行时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_tasks_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_tasks_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批任务",
                "verbose_name_plural": "审批任务",
                "db_table": "approval_tasks",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "action_code"],
                        name="approval_ta_status_ce787a_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="approval_ta_target__c4ab06_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "status"],
                        name="approval_ta_request_c82f35_idx",
                    ),
                ],
            },
        ),
    ]
