# Generated by Django 4.2.9 on 2026-03-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_approvaltask"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataConsistencyCheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual", max_length=30, verbose_name="来源"
                    ),
                ),
                (
                    "total_issues",
                    models.IntegerField(default=0, verbose_name="问题总数"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="汇总信息"),
                ),
                (
                    "issues",
                    models.JSONField(blank=True, default=list, verbose_name="问题明细"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consistency_check_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "一致性巡检记录",
                "verbose_name_plural": "一致性巡检记录",
                "db_table": "data_consistency_check_runs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="data_consis_created_ab57ff_idx"
                    ),
                    models.Index(
                        fields=["source"], name="data_consis_source_9e0f75_idx"
                    ),
                ],
            },
        ),
    ]
