# Generated by Django 4.2.9 on 2026-03-07 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_dataconsistencycheckrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferRecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("recommend", "转寄中心重推"),
                            ("create", "创建订单自动推荐"),
                            ("manual", "手工触发"),
                        ],
                        default="recommend",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                ("target_event_date", models.DateField(verbose_name="目标预定日期")),
                (
                    "target_address",
                    models.TextField(blank=True, verbose_name="目标地址"),
                ),
                (
                    "before_source_order_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="推荐前来源单ID集合"
                    ),
                ),
                (
                    "selected_source_order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="推荐后来源单ID"
                    ),
                ),
                (
                    "selected_source_order_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="推荐后来源单号",
                    ),
                ),
                (
                    "warehouse_needed",
                    models.IntegerField(default=0, verbose_name="需仓库补量"),
                ),
                (
                    "candidates",
                    models.JSONField(blank=True, default=list, verbose_name="候选快照"),
                ),
                (
                    "score_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="评分摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_recommendation_logs",
                        to="core.order",
                        verbose_name="目标订单",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_recommendation_logs",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "转寄推荐日志",
                "verbose_name_plural": "转寄推荐日志",
                "db_table": "transfer_recommendation_logs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["order", "sku", "created_at"],
                        name="transfer_re_order_i_e030fd_idx",
                    ),
                    models.Index(
                        fields=["trigger_type", "created_at"],
                        name="transfer_re_trigger_003478_idx",
                    ),
                ],
            },
        ),
    ]
