# Generated by Django 4.2.9 on 2026-03-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_transferrecommendationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaltask",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近催办时间"
            ),
        ),
        migrations.AddField(
            model_name="approvaltask",
            name="remind_count",
            field=models.IntegerField(default=0, verbose_name="催办次数"),
        ),
    ]
