# Generated by Django 4.2.9 on 2026-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_approvaltask_last_reminded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaltask",
            name="current_review_count",
            field=models.IntegerField(default=0, verbose_name="已审批人数"),
        ),
        migrations.AddField(
            model_name="approvaltask",
            name="required_review_count",
            field=models.IntegerField(default=1, verbose_name="所需审批人数"),
        ),
        migrations.AddField(
            model_name="approvaltask",
            name="review_trail",
            field=models.JSONField(blank=True, default=list, verbose_name="审批轨迹"),
        ),
        migrations.AddField(
            model_name="approvaltask",
            name="reviewed_user_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="已审批用户ID列表"
            ),
        ),
    ]
