# Generated by Django 4.2.9 on 2026-03-11 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_order_xianyu_order_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assembly_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="装配单号"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="装配套数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assembly_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assembly_orders",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "装配单",
                "verbose_name_plural": "装配单",
                "db_table": "assembly_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order_no",
                    models.CharField(max_length=50, unique=True, verbose_name="工单号"),
                ),
                ("issue_desc", models.TextField(blank=True, verbose_name="问题描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_maintenance_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完成人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_maintenance_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_work_orders",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_work_orders",
                        to="core.inventoryunit",
                        verbose_name="单套",
                    ),
                ),
            ],
            options={
                "verbose_name": "维修工单",
                "verbose_name_plural": "维修工单",
                "db_table": "maintenance_work_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWorkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "replace_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="更换数量",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "new_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_new_items",
                        to="core.part",
                        verbose_name="替换部件",
                    ),
                ),
                (
                    "old_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_old_items",
                        to="core.part",
                        verbose_name="故障部件",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.maintenanceworkorder",
                        verbose_name="维修工单",
                    ),
                ),
            ],
            options={
                "verbose_name": "维修工单明细",
                "verbose_name_plural": "维修工单明细",
                "db_table": "maintenance_work_order_items",
                "ordering": ["work_order_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_set",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="单套用量",
                    ),
                ),
                (
                    "required_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="应扣数量",
                    ),
                ),
                (
                    "deducted_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="实扣数量",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "assembly_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.assemblyorder",
                        verbose_name="装配单",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assembly_order_items",
                        to="core.part",
                        verbose_name="部件",
                    ),
                ),
            ],
            options={
                "verbose_name": "装配单明细",
                "verbose_name_plural": "装配单明细",
                "db_table": "assembly_order_items",
                "ordering": ["assembly_order_id", "part__name"],
            },
        ),
        migrations.AddIndex(
            model_name="maintenanceworkorder",
            index=models.Index(
                fields=["work_order_no"], name="maintenance_work_or_16d3bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceworkorder",
            index=models.Index(fields=["status"], name="maintenance_status_020889_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceworkorder",
            index=models.Index(fields=["unit"], name="maintenance_unit_id_1c96c0_idx"),
        ),
        migrations.AddIndex(
            model_name="assemblyorder",
            index=models.Index(
                fields=["assembly_no"], name="assembly_or_assembl_0cf621_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assemblyorder",
            index=models.Index(
                fields=["sku", "status"], name="assembly_or_sku_id_656ec6_idx"
            ),
        ),
    ]
