# Generated by Django 4.2.9 on 2026-03-11 06:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_assemblyorder_maintenanceworkorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitDisposalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposal_no",
                    models.CharField(max_length=50, unique=True, verbose_name="工单号"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("disassemble", "拆解回件"), ("scrap", "报废停用")],
                        max_length=20,
                        verbose_name="动作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("issue_desc", models.TextField(blank=True, verbose_name="原因说明")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_disposal_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完成人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_disposal_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_orders",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "单套处置工单",
                "verbose_name_plural": "单套处置工单",
                "db_table": "unit_disposal_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="source_assembly_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_units",
                to="core.assemblyorder",
                verbose_name="来源装配单",
            ),
        ),
        migrations.AlterField(
            model_name="unitmovement",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WAREHOUSE_OUT", "仓库发出"),
                    ("TRANSFER_PENDING", "转寄待执行"),
                    ("TRANSFER_SHIPPED", "转寄寄出"),
                    ("TRANSFER_COMPLETED", "转寄完成"),
                    ("RETURN_SHIPPED", "回仓在途"),
                    ("RETURNED_WAREHOUSE", "已回仓"),
                    ("MAINTENANCE_CREATED", "维修工单创建"),
                    ("MAINTENANCE_COMPLETED", "维修完成"),
                    ("UNIT_DISASSEMBLED", "单套拆解"),
                    ("UNIT_SCRAPPED", "单套报废"),
                    ("EXCEPTION", "异常"),
                ],
                max_length=30,
                verbose_name="节点类型",
            ),
        ),
        migrations.CreateModel(
            name="UnitDisposalOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="数量",
                    ),
                ),
                (
                    "returned_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="回收入库数量",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "disposal_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.unitdisposalorder",
                        verbose_name="处置工单",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_disposal_items",
                        to="core.part",
                        verbose_name="部件",
                    ),
                ),
            ],
            options={
                "verbose_name": "单套处置明细",
                "verbose_name_plural": "单套处置明细",
                "db_table": "unit_disposal_order_items",
                "ordering": ["disposal_order_id", "part__name"],
            },
        ),
        migrations.AddField(
            model_name="unitdisposalorder",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disposal_orders",
                to="core.inventoryunit",
                verbose_name="单套",
            ),
        ),
        migrations.AddIndex(
            model_name="unitdisposalorder",
            index=models.Index(
                fields=["disposal_no"], name="unit_dispos_disposa_50f954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitdisposalorder",
            index=models.Index(fields=["status"], name="unit_dispos_status_9c45db_idx"),
        ),
        migrations.AddIndex(
            model_name="unitdisposalorder",
            index=models.Index(
                fields=["action_type", "status"], name="unit_dispos_action__cbca80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitdisposalorder",
            index=models.Index(fields=["unit"], name="unit_dispos_unit_id_1970ce_idx"),
        ),
    ]
