# Generated by Django 4.2.9 on 2026-03-11 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_unitdisposalorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assemblyorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("completed", "已完成"),
                    ("reversed", "已冲销"),
                    ("cancelled", "已取消"),
                ],
                default="completed",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="unitmovement",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WAREHOUSE_OUT", "仓库发出"),
                    ("TRANSFER_PENDING", "转寄待执行"),
                    ("TRANSFER_SHIPPED", "转寄寄出"),
                    ("TRANSFER_COMPLETED", "转寄完成"),
                    ("RETURN_SHIPPED", "回仓在途"),
                    ("RETURNED_WAREHOUSE", "已回仓"),
                    ("MAINTENANCE_CREATED", "维修工单创建"),
                    ("MAINTENANCE_COMPLETED", "维修完成"),
                    ("MAINTENANCE_REVERSED", "维修工单冲销"),
                    ("UNIT_DISASSEMBLED", "单套拆解"),
                    ("UNIT_SCRAPPED", "单套报废"),
                    ("EXCEPTION", "异常"),
                ],
                max_length=30,
                verbose_name="节点类型",
            ),
        ),
        migrations.CreateModel(
            name="PartRecoveryInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="待质检数量",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待质检"),
                            ("returned", "已回库"),
                            ("repair", "待维修"),
                            ("scrapped", "已报废"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "disposal_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_inspections",
                        to="core.unitdisposalorderitem",
                        verbose_name="来源处置明细",
                    ),
                ),
                (
                    "disposal_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_inspections",
                        to="core.unitdisposalorder",
                        verbose_name="来源处置单",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_inspections",
                        to="core.part",
                        verbose_name="部件",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_part_recovery_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_recovery_inspections",
                        to="core.sku",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_inspections",
                        to="core.inventoryunit",
                        verbose_name="来源单套",
                    ),
                ),
            ],
            options={
                "verbose_name": "拆解回件质检记录",
                "verbose_name_plural": "拆解回件质检记录",
                "db_table": "part_recovery_inspections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="part_recove_status_4b0a49_idx",
                    ),
                    models.Index(
                        fields=["part", "status"], name="part_recove_part_id_4a4aff_idx"
                    ),
                    models.Index(
                        fields=["unit"], name="part_recove_unit_id_33ea84_idx"
                    ),
                ],
            },
        ),
    ]
