# Generated by Django 4.2.9 on 2026-03-22 10:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_order_return_service_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SKUImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="sku_images/", verbose_name="图片"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="是否封面"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "SKU展示图片",
                "verbose_name_plural": "SKU展示图片",
                "db_table": "sku_images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WechatCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="微信OpenID",
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="微信UnionID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=100, verbose_name="昵称"),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="头像URL")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="手机号"),
                ),
                (
                    "wechat_id",
                    models.CharField(blank=True, max_length=100, verbose_name="微信号"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次访问"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最近访问"),
                ),
            ],
            options={
                "verbose_name": "微信客户",
                "verbose_name_plural": "微信客户",
                "db_table": "wechat_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="financetransaction",
            new_name="finance_tra_reserva_722817_idx",
            old_name="finance_tra_reserva_7edc4a_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_order_s_15bd6d_idx",
            old_name="orders_order_source_952ff0_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_source__4b7d66_idx",
            old_name="orders_source_order_no_c15027_idx",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_reserva_f2bbcf_idx",
            old_name="reservations_reserva_047526_idx",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_status_a87326_idx",
            old_name="reservations_status_232fe2_idx",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_event_d_84578e_idx",
            old_name="reservations_event_d_3b99c0_idx",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_custome_cfdc25_idx",
            old_name="reservations_custome_b90189_idx",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_owner_i_90f6a6_idx",
            old_name="reservations_owner_id_5e7d4e_idx",
        ),
        migrations.AddField(
            model_name="reservation",
            name="source",
            field=models.CharField(
                choices=[("manual", "客服录入"), ("miniprogram", "小程序")],
                default="manual",
                max_length=20,
                verbose_name="来源渠道",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="display_stock",
            field=models.IntegerField(
                default=0,
                help_text="小程序展示用，手动设置，不影响真实库存",
                verbose_name="展示库存",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="display_stock_warning",
            field=models.IntegerField(
                default=0,
                help_text="低于此值时小程序显示即将售罄",
                verbose_name="展示库存预警线",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="mp_sort_order",
            field=models.IntegerField(
                default=0,
                help_text="小程序产品列表排序，数字越小越靠前",
                verbose_name="小程序排序",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="mp_visible",
            field=models.BooleanField(
                default=False,
                help_text="控制是否在小程序中展示",
                verbose_name="小程序可见",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_source",
            field=models.CharField(
                choices=[
                    ("wechat", "微信成交"),
                    ("xianyu", "闲鱼"),
                    ("xiaohongshu", "小红书"),
                    ("miniprogram", "小程序"),
                    ("other", "其他"),
                ],
                default="wechat",
                max_length=20,
                verbose_name="订单来源",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="订金金额",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="quantity",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="数量",
            ),
        ),
        migrations.AddIndex(
            model_name="sku",
            index=models.Index(
                fields=["mp_visible", "mp_sort_order"], name="skus_mp_visi_92518e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wechatcustomer",
            index=models.Index(fields=["openid"], name="wechat_cust_openid_b01bef_idx"),
        ),
        migrations.AddIndex(
            model_name="wechatcustomer",
            index=models.Index(fields=["phone"], name="wechat_cust_phone_9ccd2a_idx"),
        ),
        migrations.AddField(
            model_name="skuimage",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.sku",
                verbose_name="SKU",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="wechat_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="core.wechatcustomer",
                verbose_name="小程序客户",
            ),
        ),
    ]
