# Generated by Django 4.2.9 on 2026-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_miniprogram_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="delivery_address",
            field=models.TextField(blank=True, verbose_name="收货地址"),
        ),
    ]
